### ISSUE TITLE
Error when attempting to run a new nodeonfire application

### ISSUE THREAD

**Issue by mrnil** [martijndeh/fire#14]
Hi there,

I've just installed node on fire, created an app and tried to run it.  The following is the resulting error : 

```
sudo fire run
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/fire/node_modules/.bin/nf ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3
```

I'm currently running node 5.1.0 on macOS, but I have tried 4.2.2 LTS as well.

**Comment by euchrid** [comment]
Same issue on 5.3 and tried rolling back to 5.1.1

Any thoughts?

**Comment by iamgutz** [comment]
This is not working for me either. I get the same error when "fire run". Can you fix?

**Comment by 1Map** [comment]
+1

**Comment by martijndeh** [comment]
Sorry for the late reply. This issue is not relevant anymore. Please have a look at the new version.
